const actionTypes = {
  ASYNC_FETCH_WEATHER_DATA: "ASYNC_FETCH_WEATHER_DATA",
  ASYNC_FETCH_WEATHER_DATA_FAILURE: "ASYNC_FETCH_WEATHER_DATA_FAILURE",
  ASYNC_FETCH_WEATHER_DATA_SUCCESS: "ASYNC_FETCH_WEATHER_DATA_SUCCESS",

  ASYNC_FETCH_LOCATION_COORDINATES: "ASYNC_FETCH_LOCATION_COORDINATES",
  ASYNC_FETCH_LOCATION_COORDINATES_FAILURE:
    "ASYNC_FETCH_LOCATION_COORDINATES_FAILURE",
  ASYNC_FETCH_LOCATION_COORDINATES_SUCCESS:
    "ASYNC_FETCH_LOCATION_COORDINATES_SUCCESS",
};

export default actionTypes;
