const actionTypes = {
  ASYNC_FETCH_DATA: "ASYNC_FETCH_DATA",
  ASYNC_FETCH_DATA_FAILURE: "ASYNC_FETCH_DATA_FAILURE",
  ASYNC_FETCH_DATA_SUCCESS: "ASYNC_FETCH_DATA_SUCCESS",
};

export default actionTypes;
